apiVersion: apps/v1alpha1
kind: PetSet

metadata:
  name: prometheus-frontend 

spec:
  replicas: 1 
  serviceName: prometheus-frontend
  template:
    metadata:
      labels:
        app: prometheus
        type: frontend
    spec:
      terminationGracePeriodSeconds: 600
      containers:
        - name: prometheus 
          image: "{{.Values.image}}"
          args:
            - -config.file=/etc/prometheus/prometheus.yaml
            - -storage.local.path=/prometheus
            - -storage.local.target-heap-size=={{.Values.target_heap_size}}
            - -storage.local.retention={{.Values.retention}}
            - -web.console.libraries=/etc/prometheus/console_libraries
            - -web.console.templates=/etc/prometheus/consoles
            - -web.external-url=https://prometheus.{{.Values.global.region}}.{{.Values.global.domain}}
          ports:
            - name: http 
              containerPort: 9090
          volumeMounts:
            - name: data
              mountPath: /prometheus
            - name: config
              mountPath: /etc/prometheus
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data 
        - name: config
          configMap:
            name: prometheus-frontend
  volumeClaimTemplates:
    - metadata:
        name: data 
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 300Gi
