apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: prometheus-collector 

spec:
  replicas: 1 
  selector:
    matchLabels:
      app: prometheus
      type: collector
  template:
    metadata:
      labels:
        app: prometheus
        type: collector
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: prometheus 
          image: "{{.Values.image}}"
          args:
            - -config.file=/etc/prometheus/prometheus.yaml
            - -storage.local.path=/prometheus
            - -storage.local.target-heap-size=={{.Values.target_heap_size}}
            - -storage.local.retention={{.Values.retention}}
            - -web.console.libraries=/etc/prometheus/console_libraries
            - -web.console.templates=/etc/prometheus/consoles
          ports:
            - name: http 
              containerPort: 9090
          volumeMounts:
            - name: data
              mountPath: /prometheus
            - name: config
              mountPath: /etc/prometheus
      volumes:
        - name: data
          emptyDir: 
            medium: Memory
        - name: config
          configMap:
            name: prometheus-collector

